projectceladon/vendor-intel-utils-vertical-iot

bsp_diff/caas/device/intel/civ/host/vm-manager/0003-SDE-FRP-vm-manager-start_civ.sh-changes.patch, bsp_diff/caas/device/intel/civ/host/vm-manager/0006-Revert-Upgrade-the-qemu4.2-to-6.0-and-add-SRIOV-chan.patch, bsp_diff/caas/vendor/intel/utils/0001-Revert-Upgrade-the-qemu-4.2-to-6.0-patches.patch
Issue with Qemu 6.0 in TPY branch.So changing back to qemu4.2.
Tracked-On: OAM-102241
Signed-off-by: gollarx <ratnakumarix.golla@intel.com>
=>  Qemu version revert 6.0 to 4.2

bsp_diff/caas/device/intel/mixins/0042-ADL-Android-S-Media-Performance-range-fix.patch, bsp_diff/caas/device/intel/project-celadon/0046-Mixin-up-patch-for-Media-performace-fix.patch
=> [ADL Android-S] Media Performance range fix

bsp_diff/caas/device/intel/civ/host/vm-manager/0039-Update-SRIOV-QEMU-patching.patch
Patch derived from
https://github.com/intel-innersource/os.android.bsp.vendor-intel-vertical-utils/pull/366
Tracked-On: OAM-105674
Signed-off-by: Chenthati, Pradeep <pradeepx.chenthati@intel.com>
=> Added patch for SRIOV QEMU CVE patch

bsp_diff/caas/device/intel/civ/host/vm-manager/0040-Remove-user-prompts-from-host-setup.patch
PR#367 ported to Android 12 SMR0/Branch
Tracked-On: OAM-105716
=> Remove user prompts from host setup

bsp_diff/caas/device/intel/mixins/0043-ADL-WW05-Media-performance-range-fix.patch, bsp_diff/caas/device/intel/project-celadon/0047-Mixin-update-for-Media-performance-range-for-ww05.patch
=> [ADL] Media prformance range fix for ww05

bsp_diff/caas/device/intel/civ/host/vm-manager/0041-VM_MANAGER_VERSION-change-to-celadon-s-mr0-stable-in.patch
Fix for s/w to h/w codec in vertical build.
Tracked-On: OAM-106631
=> VM_MANAGER_VERSION change to celadon/s/mr0/stable in setup_host.sh

bsp_diff/caas/device/intel/civ/host/vm-manager/0042-Skip-QEMU-installation-for-RPL-P-during-host-setup.patch
--bsp to be passed as an argument when running on RPL-P. Eg. sudo -E ./scripts/setup_host.sh --bsp
Tracked-On: OAM-106817
=> Skip QEMU installation for RPL-P during host setup.

bsp_diff/caas/device/intel/civ/host/vm-manager/0043-Switch-to-using-split-OVMF.patch
Changes:
- updated setup script to copy split OVMF files
- configured ini script to use split OVMF
Tracked-On: OAM-106965
=> Switch to using split OVMF

bsp_diff/caas/device/intel/civ/host/vm-manager/0045-Add-parameter-to-disable-host-input.patch, host/vm-manager/0002-Disable-host-input-on-Android-CIV.patch
- Disable host input based on value from ini file.
Tracked-On: OAM-110573
=> Disable host input on Android CIV

host/vm-manager/0003-Revert-Disable-PMU-emulation-for-guest-in-case-of-vm.patch
unable to find the operating system in a/b slots
Tracked-On: OAM-110665
=> Android launch fails on rpl-s platform

host/vm-manager/0003-Update-preempt_timeout_us-and-exec_quantum_ms-based-.patch, host/vm-manager/0004-Limit-number-of-VFs-to-4-for-C0-stepping.patch
=> Add support for 6.1 kernel

bsp_diff/caas/device/intel/civ/host/vm-manager/0046-Multi-Android-VM-support.patch, bsp_diff/caas/device/intel/mixins/0044-Multi-Android-VM-support.patch
- Support execution of multiple Android CIV VMs simultaneously.
Tracked-On: OAM-110639
=> Add support for Multi Android VM support

bsp_diff/caas/hardware/intel/external/libva/0001-Clang-fix-for-libva.patch
=> Clang fix for libva

bsp_diff/caas/device/intel/civ/host/vm-manager/0047-Upgrade-QEMU-to-8.0.0.patch
=> Upgrade QEMU to 8.0.0

host/vm-manager/0006-Modify-preempt_timeout_us.patch
Change preempt_timeout_us from 50000 to 500000
Tracked-On: GFXSRIOV-621
=> Modify preempt_timeout_us

bsp_diff/caas/device/intel/civ/host/vm-manager/0048-Fix-TPM-error-failure-fix-for-NVIndex-failure.patch
Multi Android VM support TPM error failure fix for NVIndex failure
Tracked-On: OAM-111783
=> Fix TPM error failure fix for NVIndex failure

bsp_diff/caas/device/intel/civ/host/vm-manager/0049-Fix-pip3-version-error.patch
Pick pip version and set sleep inhibitor service.
Tracked-On: OAM-112216
=> Fix pip3 version error.

bsp_diff/caas/device/intel/civ/host/vm-manager/0050-Fix-setup_host-re-run-issues.patch
- Fix bugs in vm-manager installation
- Handle Android-CIV folder creation failure
Tracked-On: OAM-112228
=> Fix setup_host re-run issues

bsp_diff/caas/device/intel/mixins/0045-Include-sample_encode-and-sample_decode-as-part-of-b.patch
Include sample encode/decode files in vendor image.
Tracked-On: OAM-112315
=> Include sample encode/decode files in image

host/vm-manager/0009-Fix-issue-with-Type-C-display-monitor.patch
Add valid checks for DP ports as they are being used for Type-C ports.
Tracked-On: OAM-112494
=> Fix issue with Type-C monitor

bsp_diff/caas/device/intel/civ/host/vm-manager/0052-Revert-Update-SRIOV-QEMU-patching.patch
=> RPL_S MR3RC02 removed patch to fix setup host issue

bsp_diff/caas/device/intel/civ/host/vm-manager/0053-Upgrade-QEMU-to-8.2.1.patch, bsp_diff/caas/vendor/intel/utils/0006-Resolve-conflicts-for-QEMU-upgrade.patch
Upgrade QEMU to 8.2.1
- Upgrade QEMU to 8.2.1 from 8.0.0
- Resolve conflicts
Tracked-On: OAM-116939
Signed-off-by: Suresh, Prashanth <prashanth.suresh@intel.com>
=> Upgrade QEMU to 8.2.1

bsp_diff/caas/device/intel/civ/host/vm-manager/0054-Enable-support-for-HW-Spcie.patch, host/vm-manager/0010-Enable-support-for-HW-Spice.patch
Enable HW Spice support for Android from vm-manager
Tracked-On: OAM-117157
Signed-off-by: Suresh, Prashanth <prashanth.suresh@intel.com>
=> Enable HW Spice support on Android.

host/vm-manager/0012-Solve-mouse-lag-issue-in-Android.patch
Add render_sync=false to resolve mouse lag issue.
Tracked-On: OAM-120831
=> Resolve mouse lag issue in Android.

host/vm-manager/0012-Solve-mouse-lag-issue-in-Android.patch
Add render_sync=false to resolve mouse lag issue.
Tracked-On: OAM-121159
=> Resolve mouse lag issue in Android VM.
