projectceladon/vendor-intel-utils-vertical-iot

bsp_diff/caas/device/intel/civ/host/vm-manager/0038-Fix-logic-to-display-gvt-prompt.patch
Changes:
- improved string matching to handle both hex and decimal
- retained only SRIOV setting in string match
Change-Id: Idca0fa12a813060c6c8fc36fa19dc71fdd410d19
Tracked-On: OAM-105286
Signed-off-by: Suresh, Prashanth <prashanth.suresh@intel.com>
=> Fix logic to display gvt prompt

aosp_diff/caas/frameworks/av/0001-CCodecBufferChannel-Report-an-error-after-reallocati.patch
Output buffer conversion failures trigger endless reallocations of output buffers. Report an error in the case.
This changes are taken from horizontal celadon(Android-T).
Google source code commit reference:
https://android.googlesource.com/platform/frameworks/av/+/8ceef4d17fad183bafc2afb587bdca667c4cff1e
Tracked-On: OAM-105250
Signed-off-by: Vasoya,Nikhilx <nikhilx.vasoya@intel.com>
=> CCodecBufferChannel: Report an error after reallocation failures.

bsp_diff/caas/device/intel/mixins/0015-Config-disable-fw-cache-config.patch
as per vts kernel compatablity test suit
test case is expecting CONFIG_FW_CACHE to n
config CONFIG_FW_CACHE, value = y but required n
Tracked-On: OAM-105308
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>
=> [Config] disable fw cache config

aosp_diff/caas/packages/modules/NeuralNetworks/0001-Revert-Modify-IA-perf-variant-of-library-to-have-sam.patch, aosp_diff/caas/packages/modules/NeuralNetworks/0002-Revert-Generate-avx2-versions-of-libnueralnetworks.s.patch
IA-Perf/avx2/libneuralnetworks.so" is a public
library that was loaded from a subdirectory.
Tracked-On: OAM-105283
Signed-off-by: sushre2x sushreex.panda@intel.com
=> [NeuralNetwork] Revert Patches for Linkernamespace

bsp_diff/caas/vendor/intel/mediasdk_c2/0007-MediaSDK_C2-refactor-regression.patch
call the component’s function directly(skip codec). So that we set the outputPoolId to PLATFORM_START, it will use the BUFFERQUEUE allocator, but no surface was set. That’s why you see igbp_id is 0 and igbp_slot is ~0(0xffffffff)
Tracked-On:
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>
=> MediaSDK_C2 refactor regression.

bsp_diff/caas/vendor/intel/mediasdk_c2/0009-Change-the-MinInputBufferSize-to-1M.patch
Using 2M is with Software Codec calculation causing memory overfllow in CTS. Reduce it to 1M.
Tracked-On: OAM-105733
=> Change the MinInputBufferSize to 1M

bsp_diff/caas/vendor/intel/external/project-celadon/audio/0001-Add-getCapturePosition-implementation.patch
Add getCapturePosition method implementation in HAL added methods to calculate time and frames read.
VtsHalAudioV7_0Target Tests Fixed
Tracked-On: OAM-105777
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>
=> Add getCapturePosition implementation

bsp_diff/caas/vendor/intel/utils/0005-remove-obsolete-qemu-patch.patch
since qemu version 7.1.1 is used in vertical builds, this patch became obsolete
Tracked-On: OAM-105834
Signed-off-by: Chenthati, Pradeep <pradeepx.chenthati@intel.com>
=> remove obsolete qemu patch

bsp_diff/caas/hardware/intel/external/mesa3d-intel/0023-Iris-Fix-to-release-BO-immediately-if-not-busy.patch
Currently the iris driver is adding the buffer objects to zombie list without checking if it is busy or not. It checks for it after 1 second which adds delay to buffer release.
This fix checks if the bo is busy or not before adding it to zombie list.
Without this fix, the applications expecting immediate buffer release would fail.
The fix is identified while debugging below cts tests: android.graphics.cts.BitmapTest#testDrawingHardwareBitmapNotLeaking android.graphics.cts.BitmapTest#testHardwareBitmapNotLeaking
Tracked-On: OAM-105275
=> Iris: Fix to release BO immediately if not busy

bsp_diff/caas/vendor/intel/mediasdk_c2/0001-Resolve-the-profile-level-issue-due-to-FrameRate-con.patch
Media TC: testProfileAvcBaselineLevel1 is failed with incorrect level error due to FrameRateExtN is not configured with the TC config value.
Remove the else condition from the kParamIndexFrameRate switch case because every valid framerate it is considering as failure case and FrameRateExtN is not getting updated with the TC configration.
Tracked-On: OAM-105719
=> Resolve the profile level issue due to FrameRate config in encoder

bsp_diff/caas/hardware/intel/external/mesa3d-intel/0024-Deqp-fix-for-EXT_tooling_info.patch
Fixes CTS below failures, with implementing EXT_tooling_info
1. dEQP-VK.api.tooling_info#validate_getter
2.  3.dEQP-VK.api.tooling_info#validate_tools_properties
Taken below reference 
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15491
Tracked-On: OAM-106550
=> Deqp fix for EXT_tooling_info

bsp_diff/caas/hardware/intel/external/mesa3d-intel/0021-INTERNAL-Duplicate-fd-in-iris-driver-instead-of-reus.patch
Duplicate DRM file descriptor internally instead of reuse.
Tracked-On: OAM-105812
Signed-of-by: Shekhar Chauhan <shekhar.chauhan@intel.com>
=> INTERNAL: Duplicate fd in iris driver instead of reuse

bsp_diff/caas/vendor/intel/mediasdk_c2/0002-Exit-the-loop-when-the-surface-may-not-be-available.patch, bsp_diff/caas/vendor/intel/mediasdk_c2/0003-c2-decoder-Fixed-some-issues-when-oneVPL-returns-res.patch
case: widevineH264AdaptiveWithRendererDisablingV18
1. prevent deleting bs which in use.
2. when oneVPL returns an error of resolution change, it is not necessarily the width or height has changed. however, we reinit the codec.
3. when deleting a work if it is not found, do not return a fatal error directly.
4. Exit the loop when the surface may not be available
Tracked-On: OAM-104972
=> [c2][decoder] Fixed some issues when oneVPL returns resolution change

bsp_diff/caas/device/intel/mixins/0046-defconfig-for-5.15-yocto-kernel.patch
Change is fixing the VtsKernel Compatability test. No compatible kernel requirement found (kernel FCM version = 7). For Kernel requirements at matrix level 7, Missing config
Below VTS tests are fixed
KernelApiSysfsTest
com.android.tests.sysfs.KernelApiSysfsTest#testKfenceSampleRate
vts_treble_vintf_framework_test
SystemVendorTest#KernelCompatibility
SystemVendorTest#VendorFrameworkCompatibility
Tracked-On: OAM-108692
=> defconfig for 5.15 yocto kernel

bsp_diff/caas/device/intel/build/0001-Fix-build-failure-on-Android-13-widevine.patch
Resolve dpkg-deb error for Release builds.
Tracked-On: OAM-108763
=> Fix build failure on Android 13 widevine

aosp_diff/caas/packages/apps/Settings/01_0001-Fix-for-adb-disconnecting-during-Monkey-Test-Run.patch
When running the monkey test, its going in tethering page inside Settings app and enabling ethernet tethering. Due to get adb connection is getting lost.
Guarding ethernet tethering option when monkey test is running, it will not display ethernet tethering option during monkey test.
Tracked-On: OAM-107233
=> Fix for adb disconnecting during Monkey Test Run.

bsp_diff/caas/vendor/intel/mediasdk_c2/0004-Revert-clearing-the-input-buffers-in-decoder.patch
TC: testClearKeyPlaybackMpeg2ts is failing because Video playback is not happening due to the commit: 984a09e10f0820b43cddfbe9810dc4508c8b0794 as it is clearing the each incoming frame index's input buffer in the decoder component.
Instead of clearing the input buffers initialize the m_uInputDelay in decoder.
Tracked-On: OAM-106762
=> Revert clearing the input buffers in decoder

bsp_diff/caas/vendor/intel/mediasdk_c2/0005-c2-decoder-fix-an-issue-create-av1-decoder-using-mor.patch
case: android.media.codec.cts.MediaCodecCapabilitiesTest#testGetMaxSupportedInstances
Reduced the default value of max picture size on av1 decoder.
Tracked-On: OAM-106762
=> [c2][decoder] fix an issue create av1 decoder using more memory

host/vm-manager/0002-Accept-null-or-empty-for-show_fps.patch
Set default to off when show_fps is null or empty.
Tracked-On: OAM-109700
=> Accept null or empty for show_fps

bsp_diff/caas/kernel/lts2020-yocto-sriov/28_0028-Android-12-ADL-Bare-Metal-Boot-Issue-Fix.patch
=> fix bi_next null pointer dereference resulting in kernel panic

bsp_diff/caas/vendor/intel/external/drm-hwcomposer/0001-Fix-crash-issue-when-hot-plugout-primary-display.patch, bsp_diff/caas/vendor/intel/external/drm-hwcomposer/0002-Fix-surfaceflinger-died-with-HWC-crash-issue.patch
Fix surfaceflinger died with HWC crash issue
Fix crash issue when hot-plugout primary display
Taken changes from jira: OAM-108926 and OAM-110612
Tracked-On: OAM-111873
=> Fix VM maximize and minimize blank screen issue

host/vm-manager/0006-Dynamic-user-id-use-in-vm-manager.patch
user id hardcoding is incorrect.
Tracked-On:
=> Use dynamic user id for pulse audio in vm-manager

bsp_diff/caas/device/intel/civ/host/vm-manager/0051-Remove-firmware-update-as-it-is-part-of-kernel.patch
Firmware update is not necessary as GuC, HuC and DMC are part of host kernel.
Tracked-On: OAM-112288
=> Remove firmware update as it is part of kernel.

bsp_diff/caas/kernel/lts2020-yocto-sriov/29_0029-drm-i915-gt-Upgrade-firmware-fixed-GuC-handshake.patch
updated the GuC firmware,
To  Do initial handshake with GuC.
GuC firmware already loaded by the PF and VF must only check that interface version exposed by GuC matches VF expectations
Tracked-On: OAM-114361
=> drm/i915/gt:Upgrade firmware, fixed GuC handshake

host/vm-manager/0011-Increase-delay-to-wait-for-server-to-start.patch
First Android launch fails as server is not started within stipulated time. Increase wait time before exiting due to failure.
Tracked-On: OAM-118714
=> Increase delay to wait for server to start.
